# Generated by Django 5.1.4 on 2024-12-21 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Secteur d'activité",
                'verbose_name_plural': "Secteurs d'activité",
            },
        ),
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de fournisseur',
                'verbose_name_plural': 'Types de fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code fournisseur')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('product_types', models.TextField(verbose_name='Types de produits/services')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.businesssector', verbose_name="Secteur d'activité")),
                ('supplier_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliertype', verbose_name='Type de fournisseur')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
    ]
