# Generated by Django 5.1.4 on 2024-12-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='Date_échéance',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='product',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='quantity',
            new_name='quantité',
        ),
    ]
