# Generated by Django 5.1.4 on 2024-12-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_due_date_invoice_date_échéance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Date_échéance',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='produit',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='quantité',
            new_name='quantity',
        ),
    ]
