# Generated by Django 5.1.4 on 2024-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('client_actif', 'Client Actif'), ('client_inactif', 'Client Inactif')], default='prospect', max_length=20),
        ),
    ]
